// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdDb98I8aLY0v1OauTvvIrnDnK1SC84QY',
    appId: '1:473471001061:web:55015320989715a1f54f0c',
    messagingSenderId: '473471001061',
    projectId: 'kash-4441d',
    authDomain: 'kash-4441d.firebaseapp.com',
    storageBucket: 'kash-4441d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCypn8YJ2uUOphxgt8HGEhm0BE9JQU_NCc',
    appId: '1:473471001061:android:9e34c4366456fd72f54f0c',
    messagingSenderId: '473471001061',
    projectId: 'kash-4441d',
    storageBucket: 'kash-4441d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX93P__Kf2rT7N7KIilaNLV7aq5KBcghY',
    appId: '1:473471001061:ios:dfe404010c161cd3f54f0c',
    messagingSenderId: '473471001061',
    projectId: 'kash-4441d',
    storageBucket: 'kash-4441d.firebasestorage.app',
    iosBundleId: 'com.example.kash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX93P__Kf2rT7N7KIilaNLV7aq5KBcghY',
    appId: '1:473471001061:ios:dfe404010c161cd3f54f0c',
    messagingSenderId: '473471001061',
    projectId: 'kash-4441d',
    storageBucket: 'kash-4441d.firebasestorage.app',
    iosBundleId: 'com.example.kash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdDb98I8aLY0v1OauTvvIrnDnK1SC84QY',
    appId: '1:473471001061:web:803daaa2392b4382f54f0c',
    messagingSenderId: '473471001061',
    projectId: 'kash-4441d',
    authDomain: 'kash-4441d.firebaseapp.com',
    storageBucket: 'kash-4441d.firebasestorage.app',
  );
}
